title: Quarter Cost
author: Edgar Williams
subtitle: Reviews of 25p movies.

url: "ghostpersonthing.github.io"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/rhl-bthr"
footer_text: "Theme by rhl-bthr"

favicon_location: assets/filmquarter.jpeg

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
